server:
  port: 8082

spring:
  application:
    name: server-b
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: server-b-group
      auto-offset-reset: earliest

kafka:
  topic:
    air-quality: air-quality-topic

otel:
  exporter:
    otlp:
      endpoint: http://otel-collector:4318
  logs:
    exporter: none
  metrics:
    exporter: none
  service:
    name: server-b
